Fixes in DTPHandler.use_sendfile and Epoll.poll
giampaolo/pyftpdlib pull request #607
Opened 2023-09-14 08:18 UTC by stat1c-void

Hi!

Thanks for your awesome work on `pyftpdlib`!

Here are two fixes, quite important in some cases, gathered from our production experience.

### 1. DTPHandler.use_sendfile

In one rare case in our environment pyftpdlib went into an infinite traceback printing loop.

May be a rare thing, I suspect it was mainly because of our environment: filesystem is a NAS-backed NFS, so things happen. Basically, it went something like this from my understanding:
1. event loop tries to close a connection
2. it then tries to close opened file, but fails to do so
3. during error handling and logging, calls `get_repr_info() -> use_sendfile() -> fileno()`
4. `fileno()` fails and event is not processed
5. event tries to get processed the next tick of event loop, with similar result

This was happening many times per second. I'm going to attach a relevant traceback.

### 2. Epoll.poll

In some cases I observed infinite hanging of a connection thread. Basically, in some cases `Epoll.poll()` gets called with `timeout = 0`, but it causes it to call `self._poller.poll(-1)`. At the same time there are no more events on the socket. The timeout idler should have triggered, but the thread (we use threaded server) is stuck on `poll(-1)`.

I guess zero timeout comes from `_Scheduler.poll` when the top-most task is overdue:
```
return max(0, self._tasks[0].timeout - now)
```

Here is a `pystack` snapshot from our production env:

```
Traceback for thread 30 (python) [] (most recent call last):
    (Python) File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
        self._bootstrap_inner()
      Arguments:
        self: <Thread at 0x7f0c68e16440>
    (Python) File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
        self.run()
      Arguments:
        self: <Thread at 0x7f0c68e16440>
    (Python) File "/usr/local/lib/python3.10/threading.py", line 953, in run
        self._target(*self._args, **self._kwargs)
      Arguments:
        self: <Thread at 0x7f0c68e16440>
    (Python) File "/usr/src/app/.venv/lib/python3.10/site-packages/pyftpdlib/servers.py", line 402, in _loop
        poll(timeout=soonest_timeout)
      Arguments:
        handler: <OVFXHandler at 0x7f0c6a23d5a0>
        self: <ThreadedFTPServer at 0x7f0c6a312170>
      Locals:
        poll_timeout: 1
        soonest_timeout: 0
        sched_poll: <method at 0x7f0c67f27500>
        poll: <method at 0x7f0c67f25b40>
        ioloop: <Epoll at 0x7f0c6961bd30>
    (Python) File "/usr/src/app/.venv/lib/python3.10/site-packages/pyftpdlib/ioloop.py", line 521, in poll
        events = self._poller.poll(timeout or -1)  # -1 waits indefinitely
      Arguments:
        timeout: 0
        self: <Epoll at 0x7f0c6961bd30>
```

2023-09-14 08:20 UTC, stat1c-void commented
The mentioned traceback:
[loki-logs-export.txt](https://github.com/giampaolo/pyftpdlib/files/12606534/loki-logs-export.txt)

2023-10-01 22:51 UTC, giampaolo requested changes
Seems reasonable. I added 1 comment. Could you please update your PR? And while you're at it, also update the HISTORY file? Thanks a lot

2023-10-01 22:51 UTC, giampaolo commented on pyftpdlib/handlers.py
> +        except ValueError:
I would catch `(OSError, ValueError)` instead.

2023-10-02 15:51 UTC, stat1c-void commented on pyftpdlib/handlers.py
> +        except ValueError:
Alright, updated

2023-10-02 18:46 UTC, merged